name: Props
main: me.polaris120990.Props.Props
version: 1.1
author: polaris120990
description: >
             Give props for cool stuff players have done.
commands:
   prop:
      description: Gives a player a prop.
   propcheck:
      description: Check how many props a player has.
   propclear:
      description: Removes all props from a player.
